{
 "title": "Lustre Jobstats Detailed",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "jobid", "label": "JobID" }
  ]
 },
 "panels": [
  {
   "title": "Metadata Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum(irate(lustre_job_stats_total{component=\"mdt\", jobid=~\"$jobid\"}[1m])) by (target, operation) > 0",
       "legendFormat": "{{target}}-{{operation}}"
      }
     ]
    },
    {
     "title": "Count",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "sum(lustre_job_stats_total{component=\"mdt\", jobid=~\"$jobid\"}) by (target, operation)",
       "legendFormat": "{{target}}-{{operation}}"
      }
     ]
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Read Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(lustre_job_read_bytes_total{component=~\"ost\",jobid=~\"$jobid\"}[1m])) by (instance, target) > 0",
     "legendFormat": "{{instance}} - {{target}}"
    }
   ]
  },
  {
   "title": "Write Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(lustre_job_write_bytes_total{component=~\"ost\",jobid=~\"$jobid\"}[1m])) by (instance, target) > 0",
     "legendFormat": "{{instance}} - {{target}}"
    }
   ]
  },
  {
   "title": "Total Bytes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read Total Bytes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "lustre_job_read_bytes_total{component=~\"ost\",jobid=~\"$jobid\"} > 0",
       "legendFormat": "{{instance}} - {{target}}"
      }
     ]
    },
    {
     "title": "Write Total Bytes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "lustre_job_write_bytes_total{component=~\"ost\",jobid=~\"$jobid\"} > 0",
       "legendFormat": "{{instance}} - {{target}}"
      }
     ]
    }
   ]
  }
 ]
}