{
 "title": "Lustre-Overview",
 "description": "lustre node health, lustre file system capacity, inode number",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Health",
   "type": "status-history",
   "gridPos": { "h": 5, "w": 22, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "lustre_health_check{target=\"lustre\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Capacity Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lustre_capacity_kibibytes{component=\"ost\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Capacity Available",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lustre_available_kibibytes{component=\"ost\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Capacity Available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "expr": "lustre_capacity_kibibytes{component=\"ost\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Capacity Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "expr": "lustre_capacity_kibibytes{component=\"ost\"} - lustre_available_kibibytes{component=\"ost\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Capacity Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lustre_capacity_kibibytes{component=\"ost\"} - lustre_available_kibibytes{component=\"ost\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "inode Maximum",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lustre_inodes_maximum{component=\"ost\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "inode Available",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lustre_inodes_free{component=\"ost\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "inode Available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 6, "y": 13 },
   "targets": [
    {
     "expr": "lustre_inodes_free{component=\"ost\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "inode Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 14, "y": 13 },
   "targets": [
    {
     "expr": "lustre_inodes_maximum{component=\"ost\"} - lustre_inodes_free{component=\"ost\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "inode Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lustre_inodes_maximum{component=\"ost\"} - lustre_inodes_free{component=\"ost\"}",
     "legendFormat": "{{target}}"
    }
   ]
  }
 ]
}