{
 "title": "Lustre Exporter OSS Overview",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "group", "label": "OSS-Group", "query": "hebe_oss, hebetest_oss" },
   {
    "name": "hosts",
    "label": "Hosts",
    "query": {
     "query": "query_result(min(max_over_time(node_load1{group=\"$group\"}[$time]) >= $load) by (instance))"
    }
   },
   { "name": "load", "label": "Max Load Over Time >=", "query": "0" },
   {
    "name": "time",
    "label": "Time",
    "query": "5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "node_port", "query": "${VAR_NODE_PORT}" },
   { "name": "lustre_port", "query": "${VAR_LUSTRE_PORT}" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Load Average (1m resolution)",
   "type": "graph",
   "description": "CPU load average 1 minute with resolution for Lustre Hebe Object Store Server",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Load" }
   ],
   "targets": [
    {
     "expr": "node_load1{group=\"$group\", instance=~\"$hosts:$node_port\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Bandwith",
   "type": "graph",
   "description": "Selected File Server InfiniBand Bandwith with RDMA over all lanes on the NIC.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_infiniband_port_data_transmitted_bytes_total{group=\"$group\", instance=~\"$hosts:$node_port\"}[1m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(irate(node_infiniband_port_data_received_bytes_total{group=\"$group\", instance=~\"$hosts:$node_port\"}[1m]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Distributed Network Bandwith",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read Bandwith",
     "type": "graph",
     "description": "Transmitted File Server InfiniBand Bandwith with RDMA over all lanes on the NIC.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(node_infiniband_port_data_transmitted_bytes_total{group=\"$group\", instance=~\"$hosts:$node_port\"}[1m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Write Bandwith",
     "type": "graph",
     "description": "Received File Server InfiniBand Bandwith with RDMA over all lanes on the NIC.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(node_infiniband_port_data_received_bytes_total{group=\"$group\", instance=~\"$hosts:$node_port\"}[1m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Space Usage",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg(100 - ((lustre_available_kilobytes{group=\"$group\",instance=~\"$hosts:$lustre_port\",component=\"ost\"} / lustre_capacity_kilobytes{group=\"$group\",instance=~\"$hosts:$lustre_port\",component=\"ost\"}) * 100)) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "I-Node Usage",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg(100 - ((lustre_inodes_free{group=\"$group\",instance=~\"$hosts:$lustre_port\", component=\"ost\"} / lustre_inodes_maximum{group=\"$group\",instance=~\"$hosts:$lustre_port\",component=\"ost\"}) * 100)) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Degraded",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "expr": "max(lustre_degraded{group=\"$group\", instance=~\"$hosts:$lustre_port\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Healthy",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "expr": "lustre_health_check{group=\"$group\", instance=~\"$hosts:$lustre_port\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "LNET Errors",
   "type": "timeseries",
   "description": "Count of LNET errors",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "rate(lustre_errors_total{group=\"$group\", instance=~\"$hosts:$lustre_port\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}