{
 "title": "Lustre-Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(lustre_exporter_build_info, job)"
    }
   },
   {
    "name": "fs",
    "label": "Filesystem",
    "query": {
     "query": "label_values(lustre_stats_total, target)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Metadata operations for $fs",
   "type": "graph",
   "description": "Metadata operations per filesystem-type of operation\n\n- Which metadata filesystem has more IOPS?\n- What kind of metadata operation is causing the load?",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "repeat": "fs",
   "yaxes": [
    { "format": "ops", "label": "Ops per call" }
   ],
   "targets": [
    {
     "expr": "sum(rate(lustre_stats_total{target=~\"$fs.*\"}[120s])) by (operation)",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "sum(rate(lustre_stats_total{target=~\"$fs.*\"}[120s]))",
     "legendFormat": "AGGREGATE"
    }
   ]
  },
  {
   "title": "Metadata operations per MDS & CPU usage",
   "type": "graph",
   "description": "* Left (thick lines): IOPS per server\n* Right (thin lines): overall CPU load as %\n\n- Which server is getting saturated in terms of CPU?\n- Is it because of the high number of IOPS associated to the server?",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(lustre_stats_total{component=\"mdt\",job=~\"$server.*\"}[120s])) by (job)",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "100*(1-avg by (instance)(irate(node_cpu{mode=\"idle\",instance=~\"$server.*\"}[2m])))",
     "legendFormat": "{{instance}}-CPU usage"
    }
   ]
  },
  {
   "title": "IO bandwidth for $fs",
   "type": "graph",
   "description": "* Above 0: Write data bandwidth per filesystem and aggregated\n* Below 0: Read data bandwidth per filesystem and aggregated\n\n* Are there high data bursts?\nNote: \n* max performance for fs1 is xx GB/s\n* max performance for fs2 is yy GB/s",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 35 },
   "repeat": "fs",
   "yaxes": [
    { "format": "Bps", "label": "Read | Write" }
   ],
   "targets": [
    {
     "expr": "sum(rate(lustre_write_bytes_total{target=~\"$fs.*\"}[2m])) by (component)",
     "legendFormat": "write"
    },
    {
     "expr": "-sum(rate(lustre_read_bytes_total{target=~\"$fs.*\"}[2m])) by (component) ",
     "legendFormat": "read"
    },
    {
     "expr": "-sum(rate(lustre_read_bytes_total{component=\"ost\"}[2m]))",
     "legendFormat": "Aggregate filesystems read"
    },
    {
     "expr": "sum(rate(lustre_write_bytes_total{component=\"ost\"}[2m]))",
     "legendFormat": "Aggregate filesystems write"
    }
   ]
  },
  {
   "title": "IO bandwidth per server",
   "type": "graph",
   "description": "* Above 0: Write data bandwidth per server\n* Below 0: Read data bandwidth per server\n\n* Are all servers equally loaded?\n* Is there any kind of operation generating more load?",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "Bps", "label": "Read | Write" }
   ],
   "targets": [
    {
     "expr": "sum(rate(lustre_write_bytes_total{job=~\"$server.*\"}[2m])) by (job)",
     "legendFormat": "{{job}}-write"
    },
    {
     "expr": "-sum(rate(lustre_read_bytes_total{job=~\"$server.*\"}[2m])) by (job)",
     "legendFormat": "{{job}}-read"
    }
   ]
  },
  {
   "title": "Data IOPS for $fs",
   "type": "graph",
   "description": "* Above 0: Write data IOPS per filesystem and overall\n* Below 0: Read data IOPS per filesystem and overall\n\n- The more IOPS the more CPU load and latency. \n- High IOPS, low bandwidth usually means small IO patterns (not great)",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 83 },
   "repeat": "fs",
   "yaxes": [
    { "format": "iops", "label": "Read | Write" }
   ],
   "targets": [
    {
     "expr": "sum(rate(lustre_write_samples_total{target=~\"$fs.*-OST00.*\"}[2m])) by (component)",
     "legendFormat": "write IOPS "
    },
    {
     "expr": "-sum(rate(lustre_read_samples_total{target=~\"$fs.*-OST00.*\"}[2m])) by (component)",
     "legendFormat": "read IOPS"
    },
    {
     "expr": "sum(rate(lustre_write_samples_total{component=\"ost\"}[2m]))",
     "legendFormat": "Aggregate filesystems write IOPS"
    },
    {
     "expr": "-sum(rate(lustre_read_samples_total{component=\"ost\"}[2m]))",
     "legendFormat": "Aggregate filesystems read IOPS"
    }
   ]
  },
  {
   "title": "Capacity per device",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "percent", "label": "% capacity" }
   ],
   "targets": [
    {
     "expr": "(1-(lustre_free_kibibytes{job=~\"$server.*\"}/lustre_capacity_kibibytes{job=~\"$server.*\"}))*100",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Data IOPS per OSS and CPU usage",
   "type": "graph",
   "description": "* Above 0: Write data iops per server\n* Below 0:  Read data iops per server\n\n* Right side (thin lines): CPU load per server\n\n* Usually the more IOPS the more CPU load",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 104 },
   "yaxes": [
    { "format": "iops", "label": "Read | Write" }
   ],
   "targets": [
    {
     "expr": "-sum(rate(lustre_write_samples_total{job=~\"$server.*\"}[2m])) by (job)",
     "legendFormat": "{{job}}-write"
    },
    {
     "expr": "-sum(rate(lustre_read_samples_total{job=~\"$server.*\"}[2m])) by (job)",
     "legendFormat": "{{job}}-read"
    },
    {
     "expr": "sum(rate(lustre_write_samples_total{job=~\"$server.*\"}[2m]) + rate(lustre_read_samples_total{job=~\"$server.*\"}[2m])) by (job)",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "100*(1-avg by (instance)(irate(node_cpu{mode='idle',instance=~'$server.*'}[2m])))",
     "legendFormat": "{{instance}} CPU load"
    }
   ]
  },
  {
   "title": "Inodes usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "percent", "label": "% usage" }
   ],
   "targets": [
    {
     "expr": "(1 - (lustre_inodes_free{job=~\"$server.*\"}/lustre_inodes_maximum{job=~\"$server.*\"}))*100",
     "legendFormat": "{{target}}"
    }
   ]
  }
 ]
}